### ISSUE TITLE
MathML?

### ISSUE THREAD

**Issue by benwr** [voxpelli/webapicontroversy.com#5]
I’m not sure if MathML counts, but while it’s a web standard and implemented in Firefox (and one earlier version of Chrome), the Chrome team won’t implement it because of complexity / claimed security problems ([See Wikipedia](https://en.wikipedia.org/wiki/MathML#Browser_support))

**Comment by voxpelli** [comment]
Does look though like Igalia will pick up the MathML work in Chrome again, so seems like it will arrive there eventually: https://mathml.igalia.com/news/2021/02/15/mathml-plans-for-2021/#new
